# Generated by Django 5.0 on 2024-04-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('gambar', models.ImageField(upload_to='redaksi')),
                ('paragraf', models.TextField()),
                ('penulis', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
    ]
