# Generated by Django 5.0.3 on 2024-04-21 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_indexweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexweb',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
