# Generated by Django 5.0.3 on 2024-05-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_indexweb_options_indexweb_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexweb',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
