# Generated by Django 5.0.3 on 2024-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_indexweb_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexweb',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
